### ISSUE TITLE
Synchronise diverged changes from java driver to rust

### ISSUE THREAD

**Issue by krishnangovindraj** [vaticle/typedb-driver-java#435]
## Problem to Solve
The java driver has changed a little since work on the rust client kicked off. 

## Proposed Solution
Changes in the 'thick' section of the drivers which will be replaced by the rust library have to be ported to rust.

E.g.:
#431 ,  #432

**Comment by flyingsilverfin** [comment]
Completed in https://github.com/vaticle/typedb-driver-java/pull/434
